services:
  pedidos:
    build: ./pedidos
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      ESTOQUE_URL: http://estoque-adapter:8000
    depends_on:
      - rabbitmq
      - estoque-adapter

  notificacoes:
    build: ./notificacoes
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  estoque-legado:
    build: ./estoque_legado
    ports:
      - "8001:8000"

  estoque-adapter:
    build: ./estoque_adapter
    ports:
      - "8002:8000"
    environment:
      ESTOQUE_WSDL: http://estoque-legado:8000/?wsdl
    depends_on:
      - estoque-legado
